module Stave
  module Core
    class Lookup
      attr_reader name: Symbol
      attr_reader variant: Variant

      def initialize: (Symbol) -> void

      def self.variant: (untyped) -> void

      def self.variant?: (Symbol) -> bool

      def self.variants: -> Array[Variant]

      self.@variants: Array[Variant]

      private

      class Variant
        attr_reader name: Symbol

        def initialize: (name: Symbol) -> void
      end

      class InvalidVariantError < StandardError
        def initialize: (Symbol) -> void
      end

      def validate_variant!: -> void

      # Internal
      def new: (Symbol) -> Lookup
    end
  end
end
